name: save to jfrog'
on:
   workflow_call
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU 
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to JFrog 
        uses: docker/login-action@v1
        with:
          registry: https://actions.jfrog.io/artifactory/
          #username: ${{ secrets.JFROG_USER_WRITER }}
          #password: ${{ secrets.JFROG_PASSWORD_WRITER }}
          JF_USER: ${{ secrets.JF_USER }}
          JF_PASSWORD: ${{ secrets.JF_PASSWORD }}
          JF_ENV_1: ${{ secrets.JF_SECRET_ENV_1 }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
      -
        name: Build and push üê≥
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: https://actions.jfrog.io/artifactory//demoapp:latest
